name = "Project Lime"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8835faa0da377e2085cf6f83638dd66884df6867298cb94256763c6c2796fd54"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
