name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fac5b0ca9b1f8f3e3435d945d62f8622f39d2041bebbc92568aeb9a5165dad38"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"
