name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4ed07f799b1cb4da155238f47053f946457c81f569053b081ece87553253873"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.127"
