name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "439741bed7a52a910dd36acfb6c2e597afeb96e6f9594e21df607dfca7b3e5fe"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
