name = "Project Lime"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c23cd461868d115d399b9431ec2a8121b38f6f37b61f8a0e752969f7b3208015"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
