name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a965e7d2b013eaa40bb40642bdf0a57ff612ff59acf7f6922ec27c7519a87720"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
