name = "Project Lime"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ea47821388cded8e9252382a812b147ae3f8ed389c1c5c4f86445db3de8efed"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
