name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edc9c7ec5907c4955134b0c8e59134a03ceb9432639b81b4ef10b63886f124d0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
