name = "Project Lime"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dfecbe040d645445a3fc3b84a2bc646ab5ff812f5e07fa8689cf2346ddfe750"

[versions]
forge = "47.3.11"
minecraft = "1.20.1"
