name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aa2289b3bf4d1cdeba282b2a263d6d09f76c722e5594c8078e4a4c74d7511d1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"
