name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "120a361d141184b46083a96caa23e3f7f19bad1a0d0556f749fdf58212f76485"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
