name = "Project Lime"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fe41b564dcf7d9bd9a2b6eeddc7bce193212997e857ddebf37e7be18967c2e2"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
