name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87681314ff4b7b3dfd7b037201c9f01c45b6ad4cc187578364a2497ffd231d8e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
