name = "Project Lime"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e9dc3e92a335d52b8e63a99ff93fefae439629028bf174d8073d24cce504cf2"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
