name = "Project Lime"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f12435cb4575205eb9c98d91c51d00c3eb55700d65d11f077db02913d885c6ec"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
