name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2763b534e4e7f1674be9844b8db2c12f9f9d671ab2ada91aaf9b0f6f62a13ac"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.175"
