name = "Project Lime"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f1d7101a170a64e7348be1e5944d1c3176619d3b2bb93e40b934282731ad54a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
