name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cff18f2e7df11940bc1f6a3bb693a942231ae99f35bac4301c3148430a5b0ff0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"
