name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "499b682d8676fd2478af29a623465153c081c85de0ed095bc162f8054626ab4e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
