name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77e980eae32969e0b0569851273f285218b0784065b11eeb7d0bd44e2fed56ef"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"
