name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bcec4f67f4b138ac10c1d600f0c20f92ad6974f25af9bee0235d30141f90c6e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
