name = "Project Lime"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af8a4db5872f34edc76520cbf7ec05e44f8fc0e4e9b9ffc870af826a381dde02"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
