name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4975ddb1d8a3249af8b596a9521b044bae607d8899301c795b1e9e30ca6c98f3"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
