name = "Project Lime"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7174503278165a8141639789966dc3988ed5caad21d284daa4547bb52366b2d"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
