name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b234b854eb830b62fc2ba5a92d921d34701c7dc76a57a3cff2184e4d34618342"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
