name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbad7200fc87ab531750d026a387cf730917287e417df934169253494bae4f13"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
