name = "Project Lime"
author = "l0py2"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c98d890a2970cf3e8015ffafe90744db622edd99985552c3871c7d4f8d897b9"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
