name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65712f68d2cb1577f61b1cd8dc26d98f2921d21057c56e80d9dedd043e1b3017"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
