name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef1acf71e31153985b5c5d2ef52e1f0f854168388bebf4d3f9d2c69124417bb4"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
