name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22ba95f107491990ad614c0b95fc1bde881f67ed56403632e23809bf9467ecf3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"
