name = "Project Lime"
author = "l0py2, Lagosta4K"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8a62c6e74a2e828d597922e85c7b3fc431e69c46bf4d248d8d94abc5d888e5c"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
