#!/bin/sh

git clone https://github.com/MCModderAnchor/TACZ.git -b 1.20.1 --depth 1 tacz

BASE_DIR='./kubejs/assets/kubejs/textures/item'

mkdir -p "$BASE_DIR/gun"
mkdir -p "$BASE_DIR/ammo"
mkdir -p "$BASE_DIR/attachment"

TACZ_BASE_DIR='./tacz/src/main/resources/assets/tacz/custom/tacz_default_gun/assets/tacz/textures'

cp -rfT "$TACZ_BASE_DIR/gun/slot" "$BASE_DIR/gun"
cp -rfT "$TACZ_BASE_DIR/ammo/slot" "$BASE_DIR/ammo"
cp -rfT "$TACZ_BASE_DIR/attachment/slot" "$BASE_DIR/attachment"

rm -rf tacz
