#KubeJS Common Properties
#Mon Dec 22 14:35:20 WET 2025
matchJsonRecipes=true
allowAsyncStreams=false
announceReload=true
startupErrorGUI=true
serverOnly=false
hideServerScriptErrors=false
saveDevPropertiesInConfig=false
packmode=
ignoreCustomUniqueRecipeIds=false
creativeModeTabIcon=minecraft\:purple_dye
startupErrorReportUrl=
