//priority: 100

global.id = {
	MC: id => `minecraft:${id}`,
	M: id => `forge:${id}`,
	KJ: id => `kubejs:${id}`,
	CR: id => `create:${id}`,
	WW: id => `woodworks:${id}`,
	SP: id => `supplementaries:${id}`,
	SS: id => `suppsquared:${id}`,
	SG: id => `scguns:${id}`,
	HC: id => `handcrafted:${id}`,
	FD: id => `farmersdelight:${id}`,
	DF: id => `delightful:${id}`,
	QK: id => `quark:${id}`,
	CC: id => `create_central_kitchen:${id}`,
	CC: id => `create_connected:${id}`,
	NA: id => `create_new_age:${id}`,
	CA: id => `createaddition:${id}`,
	PG: id => `powergrid:${id}`,
	DG: id => `createdieselgenerators:${id}`,
	TC: id => `tools_complement:${id}`,
	FQ: id => `ftbquests:${id}`,
	JA: id => `jaopca:${id}`,
	BB: id => `buzzier_bees:${id}`,
	IM: id => `immersive_machinery:${id}`
};

global.tag = {
	MC: id => `#minecraft:${id}`,
	M: id => `#forge:${id}`,
	KJ: id => `#kubejs:${id}`,
	CR: id => `#create:${id}`,
	WW: id => `#woodworks:${id}`,
	SP: id => `#supplementaries:${id}`,
	SS: id => `#suppsquared:${id}`,
	SG: id => `#scguns:${id}`,
	HC: id => `#handcrafted:${id}`,
	FD: id => `#farmersdelight:${id}`,
	DF: id => `#delightful:${id}`,
	QK: id => `#quark:${id}`,
	CC: id => `#create_central_kitchen:${id}`,
	CC: id => `#create_connected:${id}`,
	NA: id => `#create_new_age:${id}`,
	CA: id => `#createaddition:${id}`,
	PG: id => `#powergrid:${id}`,
	DG: id => `#createdieselgenerators:${id}`,
	TC: id => `#tools_complement:${id}`,
	FQ: id => `#ftbquests:${id}`,
	JA: id => `#jaopca:${id}`,
	BB: id => `#buzzier_bees:${id}`,
	IM: id => `#immersive_machinery:${id}`
};