//priority: 98

global.removedItems = [
	global.id.AA('compressor'),
	global.id.AA('desh_cable'),
	global.id.AA('desh_fluid_pipe'),
	global.id.AA('energizer'),
	global.id.AA('etrionic_blast_furnace'),
	global.id.AA('etrionic_capacitor'),
	global.id.AA('fan'),
	global.id.AA('iron_plate'),
	global.id.AA('iron_rod'),
	global.id.AA('nasa_workbench'),
	global.id.AA('oil_bucket'),
	global.id.AA('ostrum_fluid_pipe'),
	global.id.AA('steel_cable'),
	global.id.AA('steel_ingot'),
	global.id.AA('steel_nugget'),
	global.id.AA('steel_plate'),
	global.id.AA('steel_rod'),
	global.id.AA('water_pump'),
	global.id.CA('alternator'),
	global.id.CA('connector'),
	global.id.CA('copper_spool'),
	global.id.CA('copper_wire'),
	global.id.CA('electric_motor'),
	global.id.CA('electrum_ingot'),
	global.id.CA('electrum_sheet'),
	global.id.CA('electrum_spool'),
	global.id.CA('electrum_wire'),
	global.id.CA('gold_spool'),
	global.id.CA('iron_rod'),
	global.id.CA('large_connector'),
	global.id.CA('redstone_relay'),
	global.id.CA('small_light_connector'),
	global.id.CA('spool'),
	global.id.CN('blank_circuit'),
	global.id.CN('copper_circuit'),
	global.id.CN('copper_wire'),
	global.id.CN('electrical_connector'),
	global.id.CN('overcharged_diamond_wire'),
	global.id.CN('overcharged_golden_wire'),
	global.id.CN('overcharged_iron_wire'),
	global.id.FD('rope'),
	global.id.FD('wheat_dough'),
	global.id.IE('nugget_copper'),
	global.id.IE('plate_copper'),
	global.id.IE('plate_gold'),
	global.id.IE('plate_iron'),
	global.id.PC('copper_nugget'),
	global.id.PC('sourdough'),
	global.id.PC('wheat_flour'),
	global.id.TZ('gun_smith_table'),
	global.id.TZ('workbench_a'),
	global.id.TZ('workbench_b'),
	global.id.TZ('workbench_c'),
];

global.removedRecipeTypes = [
	global.id.AA('compressing'),
	global.id.AA('nasa_workbench'),
	global.id.AA('alloying')
];

global.removedRecipes = [
	global.id.AA('calorite_engine'),
	global.id.AA('desh_engine'),
	global.id.AA('iron_rod'),
	global.id.AA('ostrum_engine'),
	global.id.AA('steel_engine'),
	global.id.AA('steel_rod'),
	global.id.AN('netherite_diamond_axe_smithing'),
	global.id.AN('netherite_diamond_hoe_smithing'),
	global.id.AN('netherite_diamond_pickaxe_smithing'),
	global.id.AN('netherite_diamond_shovel_smithing'),
	global.id.AN('netherite_diamond_sword_smithing'),
	global.id.AN('netherite_emerald_axe_smithing'),
	global.id.AN('netherite_emerald_hoe_smithing'),
	global.id.AN('netherite_emerald_pickaxe_smithing'),
	global.id.AN('netherite_emerald_shovel_smithing'),
	global.id.AN('netherite_emerald_sword_smithing'),
	global.id.AN('netherite_gold_axe_smithing'),
	global.id.AN('netherite_gold_hoe_smithing'),
	global.id.AN('netherite_gold_pickaxe_smithing'),
	global.id.AN('netherite_gold_shovel_smithing'),
	global.id.AN('netherite_gold_sword_smithing'),
	global.id.AN('netherite_iron_axe_smithing'),
	global.id.AN('netherite_iron_hoe_smithing'),
	global.id.AN('netherite_iron_pickaxe_smithing'),
	global.id.AN('netherite_iron_shovel_smithing'),
	global.id.AN('netherite_iron_sword_smithing'),
	global.id.CR('crafting/appliances/dough'),
	global.id.CR('industrial_iron_block_from_ingots_iron_stonecutting'),
	global.id.CR('smelting/bread'),
	global.id.CR('smoking/bread'),
	global.id.FD('wheat_dough'),
	global.id.IE('crafting/axe_steel'),
	global.id.IE('crafting/hoe_steel'),
	global.id.IE('crafting/pickaxe_steel'),
	global.id.IE('crafting/shovel_steel'),
	global.id.IE('crafting/sword_steel'),
	global.id.MC('bread'),
	global.id.MC('diamond_axe'),
	global.id.MC('diamond_hoe'),
	global.id.MC('diamond_pickaxe'),
	global.id.MC('diamond_shovel'),
	global.id.MC('diamond_sword'),
	global.id.MC('golden_axe'),
	global.id.MC('golden_hoe'),
	global.id.MC('golden_pickaxe'),
	global.id.MC('golden_shovel'),
	global.id.MC('golden_sword'),
	global.id.MC('iron_axe'),
	global.id.MC('iron_hoe'),
	global.id.MC('iron_pickaxe'),
	global.id.MC('iron_shovel'),
	global.id.MC('iron_sword'),
	global.id.MC('netherite_axe_smithing'),
	global.id.MC('netherite_hoe_smithing'),
	global.id.MC('netherite_pickaxe_smithing'),
	global.id.MC('netherite_shovel_smithing'),
	global.id.MC('netherite_sword_smithing'),
	global.id.MC('stone_axe'),
	global.id.MC('stone_hoe'),
	global.id.MC('stone_pickaxe'),
	global.id.MC('stone_shovel'),
	global.id.MC('stone_sword'),
	global.id.PC('explosion_crafting/wheat_flour'),
	global.id.PC('pressure_chamber/wheat_flour'),
	global.id.TT('hammer/andesite'),
	global.id.TT('hammer/diorite'),
	global.id.TT('hammer/granite'),
	global.id.TT('hammer/stone')
];

global.inputReplacements = new Map([
	[global.id.FD('rope'), global.tag.M('rope')],
	[global.id.FD('wheat_dough'), global.tag.M('dough/wheat')],
	[global.id.PC('sourdough'), global.tag.M('dough')],
	[global.id.PC('wheat_flour'), global.tag.M('flour')],
	[global.id.CN('copper_circuit'), global.id.CC('control_chip')],
	[global.id.CA('copper_spool'), global.id.IE('wirecoil_copper')]
]);

global.outputReplacements = new Map([
	[global.id.FD('rope'), global.id.SP('rope')],
	[global.id.FD('wheat_dough'), global.id.CR('dough')],
	[global.id.PC('wheat_flour'), global.id.CR('wheat_dough')]
]);

global.dropReplacements = new Map([
]);
