#Configuration related to Immersive Engineering wires
[wires]
	[wires.copper]
		#The percentage of power lost every 16 blocks of distance in copper wire
		#Range: 0.0 ~ 1.0
		loss = 0.0
	[wires.electrum]
		#The percentage of power lost every 16 blocks of distance in electrum wire
		#Range: 0.0 ~ 1.0
		loss = 0.0
	[wires.hv]
		#The percentage of power lost every 16 blocks of distance in hv wire
		#Range: 0.0 ~ 1.0
		loss = 0.0
