#How many marks you can draw with a single chalk. Default: 64
# Default: 64
# Range: > 0
ChalkDurability = 256
#How many glowing uses one glowing item will give.
#Default: 8
# Default: 8
# Range: 1 ~ 9999
ChalkBoxAmountPerGlowingItem = 32
#If enabled, Chalks (and Chalk Boxes) will generate in Dungeons, Abandoned Mineshafts, Villages (Planes and Savanna), Cartographer village houses
#Default: true
GenerateChalkInLootChests = false
