#How many marks you can draw with a single chalk. Default: 64
#Range: > 0
ChalkUses = 1024
#How many glowing uses one glowing item will give.
#Default: 8
#Range: 1 ~ 9999
ChalkBoxGlowingItemUses = 256
#If enabled, Chalks (and Chalk Boxes) will generate in Dungeons, Abandoned Mineshafts, Planes and Savanna villages, Cartographer houses
#Default: true
ShouldGenerateInChests = false
