#Responsible for how much energy is generated per 1 stress unit in a tick
#Default value is supposed to be compatible with default configuration of Create: Crafts and Additions
#Range: 0.0 ~ 1.7976931348623157E308
suToEnergy = 0.03125
#How many coils can the carbon brushes collect energy from
#Range: > 0
maxCoils = 16
#How many reactor rods can a fuel inserter or a heat vent have in a single direction
#Range: > 0
maxRodsInDirection = 32
#Multiplier of wire conductivity
#Range: 0.0 ~ 1.7976931348623157E308
conductivityMultiplier = 4.0
#Maximum depth of network pathfinding
#Range: > 1
maxPathfindingDepth = 4096
#Maximum wire length
#Range: > 1
maxWireLength = 32
