[wires]
	#Small Connector max wire length in blocks.
	#Range: 0 ~ 256
	small_connector_wire_length = 16
	#Small Connector max input in FE/t (Energy transfer).
	#Range: > 0
	small_connector_max_input = 1024
	#Small Connector max output in FE/t (Energy transfer).
	#Range: > 0
	small_connector_max_output = 1024
	#Large Connector max wire length in blocks.
	#Range: 0 ~ 256
	large_connector_wire_length = 32
	#Large Connector max input in FE/t (Energy transfer).
	#Range: > 0
	large_connector_max_input = 4096
	#Large Connector max output in FE/t (Energy transfer).
	#Range: > 0
	large_connector_max_output = 4096
	#Allows blocks attached to a connector to freely pass energy to and from the connector network.
	connector_allow_passive_io = false

#Portable Energy Interface
[portable_energy_interface]
	#PEI max output in FE/t (Energy transfer).
	#Range: > 0
	pei_max_output = 4096
	#PEI max input in FE/t (Energy transfer).
	#Range: > 0
	pei_max_input = 4096

#Accumulator
[accumulator]
	#Accumulator internal capacity per block in FE.
	#Range: > 0
	accumulator_capacity = 10000000
	#Accumulator max input in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_input = 4096
	#Accumulator max output in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_output = 4096
