#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Mar 27 16:52:10 WET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.7.1.zip
enableShaders=true
