#!/bin/sh

cd ..

packwiz refresh

KUBEJS_DIR="$HOME/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Project Lime/minecraft/kubejs"

rm -rf "$KUBEJS_DIR"
cp -r ./kubejs "$KUBEJS_DIR"
